package com.pixelbloom.orders.enums;

public enum OrderStatus {
    CREATED,
    CONFIRMED,
    CANCELLED,
    SHIPPED,
    DELIVERED,
    REFUNDED,
    FAILED,
    RETURNED,
    INSPECTION_PENDING,
    RETURN_APPROVED,
    RETURN_REJECTED,
    RETURN_REQUESTED,
    DAMAGE_DECLARED,
    INSPECTION_APPROVED,
    INSPECTION_REJECTED,
    REFUND_INITIATED,
    INSPECTION_FAILED,
    RETURN_WINDOW_EXPIRED,
    RETURN_WINDOW_VALID,
    RETURN_WINDOW_NOT_VALID,
    RETURN_CATEGORY_NOT_ALLOWED,
    INSPECTION_REQUESTED, RETURN_INITIATED, RETURN_CATEGORY_ALLOWED
}
