package com.pixelbloom.orders.enums;
public enum ReturnStatus {
    INITIATED,
    PROCESSING,
    COMPLETED,
    INSPECTION_PENDING, REJECTED,
    RETURN_APPROVED, RETURN_REJECTED,
    RETURN_WINDOW_EXPIRED, RETURN_CATEGORY_NOT_ALLOWED,
    RETURN_PARTIALLY_APPROVED, INSPEC_PARTIALLY_APPROVED,
    INSPECTION_REJECTED, RETURN_INITIATED, INSPECTION_APPROVED, RETURN_REQUESTED, INSPECTION_FAILED, PARTIALLY_APPROVED
}

